name: Lewandowski Artur
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#ffffff'
    - '#a5a5a5'
    - '#555555'
    - '#7d7d7d'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
